# Решение Виталия через дипсик

1 Задание

In [ ]:
import numpy as np
damage = [5, 10, 13, 16, 20] # ущерб по категориям
expenses = [2, 4, 6, 8, 10] # затраты на дамбы


# создаем матрицу
damb = 5 # дамбы
flood = 5 # категория наводнения

matrix = np.zeros((damb, flood)) # нулевая матрица 5х5, по вертикали высота дамбы, по горизонтали может ли наводнение пробить дамбу

for i in range(damb):    # Перебор дамб (h1-h5)
    for j in range(flood):    # Перебор категорий наводнения (1-5)
        if (j + 1) <= (i + 1):   # Если дамба защищает
            matrix[i, j] = -expenses[i]
        else:                     # Если не защищает
            matrix[i, j] = -(damage[j] + expenses[i])


print("Матрица выигрышей/потерь:")
print(matrix)

# Критерии
def laplace(matrix):
    return np.argmax(np.mean(matrix, axis=1)) # средний результат

def wald(matrix):
    return np.argmax(np.min(matrix, axis=1)) # берем худший случай (наводнение 5) и выбираем высоту с наименьшими потерями

def maximax(matrix):
    return np.argmax(np.max(matrix, axis=1)) # берем лучший вариант (наводнение 1) и выбираем наилучший вариант

def savage(matrix):
    losses = np.max(matrix, axis=0) - matrix # матрица потерь
    print("Матрица потерь:")
    print(losses)
    return np.argmin(np.max(losses, axis=1)) # ищем минимальное упущение

def hurwitz(matrix, alpha):
    hurwitz_values = alpha * np.max(matrix, axis=1) + (1 - alpha) * np.min(matrix, axis=1)
    print(f"Значения по Гурвицу: {hurwitz_values}")
    return np.argmax(hurwitz_values) # среднее между wald и maximax


print("\nОптимальные решения:")
print(f"Лапласа: h{laplace(matrix) + 1}")
print(f"Вальда: h{wald(matrix) + 1}")
print(f"Максимакса: h{maximax(matrix) + 1}")
print(f"Сэвиджа: h{savage(matrix) + 1}")
print(f"Гурвица: h{hurwitz(matrix, 0.7) + 1}")

Матрица выигрышей/потерь:
[[ -2. -12. -15. -18. -22.]
 [ -4.  -4. -17. -20. -24.]
 [ -6.  -6.  -6. -22. -26.]
 [ -8.  -8.  -8.  -8. -28.]
 [-10. -10. -10. -10. -10.]]

Оптимальные решения:
Лапласа: h5
Вальда: h5
Максимакса: h1
Матрица потерь:
[[ 0.  8.  9. 10. 12.]
 [ 2.  0. 11. 12. 14.]
 [ 4.  2.  0. 14. 16.]
 [ 6.  4.  2.  0. 18.]
 [ 8.  6.  4.  2.  0.]]
Сэвиджа: h5
Значения по Гурвицу: [ -8. -10. -12. -14. -10.]
Гурвица: h1


# Моё решение. Не успел его доделать.

2 задание

In [ ]:
#  Постройте матрицу выигрышей / потерь. Найдите оптимальные решения,
# используя критерии Лапласа, Вальда, максимакса, Сэвиджа, Гурвица (оптимизм α = 0.7).
Alpha = 0.7
Pi =[30, 80, 50, 200, 380]
Ci = [14, 6, 10, 5, 4]
Q = [i for i in range(150,350+1,50)]
# Q = [150, 200, 250, 300, 350]



[30, 80, 50, 200, 380]


In [ ]:
Matrix = []
for i in range(len(Pi)):
    temp = []
    for j in range(len(Q)):
        temp.append(-(Pi[i]+ Ci[i]*Q[j]))
    Matrix.append(temp)
for i in Matrix:
    print(i)

[-2130, -2830, -3530, -4230, -4930]
[-980, -1280, -1580, -1880, -2180]
[-1550, -2050, -2550, -3050, -3550]
[-950, -1200, -1450, -1700, -1950]
[-980, -1180, -1380, -1580, -1780]


In [ ]:
def SredV(matrix):
    k = []
    for i in range(len(matrix)):
        temp = 0
        for j in range(len(matrix[i])):
            temp += matrix[i][j]
        k.append(temp)
    print(k)
    index = k.index(max(k))
    return(index+1)



In [ ]:
def Laplace(matrix):
    k = []
    for i in range(len(matrix)):
        temp = 0
        for j in range(len(matrix[i])):
            temp += matrix[i][j]
        temp = temp/len(matrix[i])
        k.append(temp)
    print(k)
    index = k.index(max(k))
    return(index+1)

In [ ]:
def MaxiMin(matrix):
    k = []
    for i in range(len(matrix)):
        k.append(min(matrix[i]))
    print(k)
    index = k.index(max(k))
    return(index+1)


In [ ]:
def MaxiMax(matrix):
    k = []
    for i in range(len(matrix)):
        k.append(max(matrix[i]))
    print(k)
    index = k.index(max(k))
    return(index+1)


In [ ]:
def Hurvicz(matrix):
    k = []
    for i in range(len(matrix)):
        a = alpha*max(matrix[i]) +(1-alpha)*min(matrix[i])
        k.append(a)
    print(k)
    index = k.index(max(k))
    return(index+1)

In [ ]:
def MiniMax(matrix):
    k = []
    for i in range(len(matrix)):
        temp = []
        print(max(matrix[i]))
        for j in range(len(matrix[i])):
            temp.append(max(matrix[i]) - matrix[i][j])
        k.append(temp)
    for i in k:
        print(i)
    temp = []
    for i in k:
        temp.append(max(i))
    print(temp)
    index = temp.index(max(temp))
    return(index+1)
print(MiniMax(Matrix))


-2130
-980
-1550
-950
-980
[0, 700, 1400, 2100, 2800]
[0, 300, 600, 900, 1200]
[0, 500, 1000, 1500, 2000]
[0, 250, 500, 750, 1000]
[0, 200, 400, 600, 800]
[2800, 1200, 2000, 1000, 800]
1


In [ ]:
print(savage(Matrix))

Матрица потерь:
[[1180 1650 2150 2650 3150]
 [  30  100  200  300  400]
 [ 600  870 1170 1470 1770]
 [   0   20   70  120  170]
 [  30    0    0    0    0]]
4


In [ ]:
print("Среднее значение")
print(SredV(Matrix))
print()
print("Критерий Лапласа")
print(Laplace(Matrix))
print()
print("Критерий максимина")
print(MaxiMin(Matrix))
print()
print("Критерий максимакса")
print(MaxiMax(Matrix))
print()
print("Критерий Гурвица")
print(Hurvicz(Matrix))
print()
print("Критерий минимакса")
print(MiniMax(Matrix))

Среднее значение
[-17650, -7900, -12750, -7250, -6900]
5

Критерий Лапласа
[-3530.0, -1580.0, -2550.0, -1450.0, -1380.0]
5

Критерий максимина
[-4930, -2180, -3550, -1950, -1780]
5

Критерий максимакса
[-2130, -980, -1550, -950, -980]
4

Критерий Гурвица
[-2970.0, -1340.0, -2150.0, -1250.0, -1220.0]
5

Критерий минимакса
[2800, 1200, 2000, 1000, 800]
1


In [ ]:
import numpy as np

# Данные из задачи
P = np.array([30, 80, 50, 200, 380])  # Стоимость пуско-наладочных работ на станке i
C = np.array([14, 6, 10, 5, 4])  # Расходы на изготовление партии изделий на станке i

# Матрица выигрышей/потерь
K = P + C * np.array([150, 200, 250, 300, 350])
K

array([2130, 1280, 2550, 1700, 1780])